import { loadConfig } from "./config";
import { pgUnsafe } from "./db/pg";
import { getSqlite } from "./db/sqlite";
import { writeFileSync } from "fs";

interface DirRow {
  dir_path: string;
  summary: string | null;
}

interface FileRow {
  file_path: string;
  file_type: string;
}

interface PgRepoRow {
  id: string;
}

interface SqliteRepoRow {
  id: number;
}

interface SqliteDirRow {
  dir_path: string;
  summary: string | null;
}

interface SqliteFileRow {
  file_path: string;
  file_type: string;
}

function countSlashes(s: string): number {
  let count = 0;
  for (const ch of s) {
    if (ch === "/") count++;
  }
  return count;
}

function extractFileName(filePath: string): string {
  const parts = filePath.split("/");
  return parts[parts.length - 1];
}

function isChildOf(filePath: string, dirPath: string): boolean {
  if (dirPath === ".") {
    // Root directory: immediate children have no "/"
    return !filePath.includes("/");
  }
  const prefix = dirPath.endsWith("/") ? dirPath : dirPath + "/";
  if (!filePath.startsWith(prefix)) return false;
  const rest = filePath.slice(prefix.length);
  return !rest.includes("/");
}

function summaryNeedsReview(summary: string | null): boolean {
  return summary === null || summary.length < 20;
}

function formatDirPath(dirPath: string): string {
  if (dirPath === ".") return "./";
  return dirPath.endsWith("/") ? dirPath : dirPath + "/";
}

async function intentPg(repoRoot: string): Promise<{ dirs: DirRow[]; files: FileRow[] }> {
  const repoRows = (await pgUnsafe(`SELECT id FROM repos WHERE root_path = $1`, [
    repoRoot,
  ])) as PgRepoRow[];

  if (repoRows.length === 0) {
    throw new Error(`Repo not found for path: ${repoRoot}`);
  }

  const repoId = parseInt(repoRows[0].id);

  const dirs = (await pgUnsafe(
    `SELECT dir_path, summary FROM directories WHERE repo_id = $1 ORDER BY dir_path`,
    [repoId],
  )) as DirRow[];

  const files = (await pgUnsafe(
    `SELECT file_path, file_type FROM files WHERE repo_id = $1 ORDER BY file_path`,
    [repoId],
  )) as FileRow[];

  return { dirs, files };
}

async function intentSqlite(repoRoot: string): Promise<{ dirs: DirRow[]; files: FileRow[] }> {
  const db = await getSqlite(repoRoot);

  const repoRows = db
    .prepare(`SELECT id FROM repos WHERE root_path = ?`)
    .all(repoRoot) as SqliteRepoRow[];

  if (repoRows.length === 0) {
    throw new Error(`Repo not found for path: ${repoRoot}`);
  }

  const repoId = repoRows[0].id;

  const dirs = db
    .prepare(`SELECT dir_path, summary FROM directories WHERE repo_id = ? ORDER BY dir_path`)
    .all(repoId) as SqliteDirRow[];

  const files = db
    .prepare(`SELECT file_path, file_type FROM files WHERE repo_id = ? ORDER BY file_path`)
    .all(repoId) as SqliteFileRow[];

  return { dirs, files };
}

export async function generateIntent(repoRoot: string, outPath?: string): Promise<string> {
  const config = await loadConfig(repoRoot);

  let dirs: DirRow[];
  let files: FileRow[];

  if (config.store === "pg") {
    ({ dirs, files } = await intentPg(repoRoot));
  } else {
    ({ dirs, files } = await intentSqlite(repoRoot));
  }

  // Sort directories by depth (number of slashes), shallowest first
  dirs.sort((a, b) => countSlashes(a.dir_path) - countSlashes(b.dir_path));

  const lines: string[] = [];
  lines.push("# AGENTS.md");
  lines.push("");
  lines.push("> Auto-generated by `codeindex intent`. Do not edit manually.");
  lines.push("> Re-generate with: `codeindex intent --out AGENTS.md`");

  for (const dir of dirs) {
    lines.push("");

    const header = formatDirPath(dir.dir_path);
    const reviewTag = summaryNeedsReview(dir.summary) ? " [REVIEW]" : "";
    lines.push(`## ${header}${reviewTag}`);
    lines.push("");

    if (dir.summary && dir.summary.length > 0) {
      lines.push(dir.summary);
    }

    // Find immediate child files
    const childFiles = files
      .filter((f) => isChildOf(f.file_path, dir.dir_path))
      .map((f) => extractFileName(f.file_path));

    if (childFiles.length > 0) {
      lines.push("");
      lines.push(`**Files:** ${childFiles.join(", ")}`);
    }
  }

  lines.push("");

  const output = lines.join("\n");

  if (outPath) {
    writeFileSync(outPath, output, "utf-8");
    process.stderr.write(`Wrote AGENTS.md to ${outPath}\n`);
  }

  return output;
}
