import { requireRepoId } from "./db/repo-lookup";
import { getStoreOps } from "./repo";
import { writeFileSync } from "fs";

interface DirRow {
  dir_path: string;
  summary: string | null;
}

interface FileRow {
  file_path: string;
  file_type: string;
}

function countSlashes(s: string): number {
  let count = 0;
  for (const ch of s) {
    if (ch === "/") count++;
  }
  return count;
}

function summaryNeedsReview(summary: string | null): boolean {
  return summary === null || summary.length < 20;
}

function formatDirPath(dirPath: string): string {
  if (dirPath === ".") return "./";
  return dirPath.endsWith("/") ? dirPath : dirPath + "/";
}

export async function generateIntent(repoRoot: string, outPath?: string): Promise<string> {
  const repoId = await requireRepoId(repoRoot, undefined, `Repo not found for path: ${repoRoot}`);
  const { ops } = await getStoreOps(repoRoot);

  const dirs = await ops.query<DirRow>(
    `SELECT dir_path, summary FROM directories WHERE repo_id = $1 ORDER BY dir_path`,
    [repoId],
  );
  const files = await ops.query<FileRow>(
    `SELECT file_path, file_type FROM files WHERE repo_id = $1 ORDER BY file_path`,
    [repoId],
  );

  // Sort directories by depth (number of slashes), shallowest first
  const sortedDirs = [...dirs].sort((a, b) => countSlashes(a.dir_path) - countSlashes(b.dir_path));

  const headerLines = [
    "# AGENTS.md",
    "",
    "> Auto-generated by `codeindex intent`. Do not edit manually.",
    "> Re-generate with: `codeindex intent --out AGENTS.md`",
  ];

  // Pre-group files by parent directory in O(files)
  const filesByDir = new Map<string, string[]>();
  for (const f of files) {
    const slashIdx = f.file_path.lastIndexOf("/");
    const parentDir = slashIdx === -1 ? "." : f.file_path.slice(0, slashIdx);
    const fileName = slashIdx === -1 ? f.file_path : f.file_path.slice(slashIdx + 1);
    let bucket = filesByDir.get(parentDir);
    if (!bucket) {
      bucket = [];
      filesByDir.set(parentDir, bucket);
    }
    bucket.push(fileName);
  }

  const dirSections = sortedDirs.flatMap((dir) => {
    const header = formatDirPath(dir.dir_path);
    const reviewTag = summaryNeedsReview(dir.summary) ? " [REVIEW]" : "";

    const childFiles = filesByDir.get(dir.dir_path) ?? [];

    return [
      "",
      `## ${header}${reviewTag}`,
      "",
      ...(dir.summary && dir.summary.length > 0 ? [dir.summary] : []),
      ...(childFiles.length > 0 ? ["", `**Files:** ${childFiles.join(", ")}`] : []),
    ];
  });

  const output = [...headerLines, ...dirSections, ""].join("\n");

  if (outPath) {
    writeFileSync(outPath, output, "utf-8");
    process.stderr.write(`Wrote AGENTS.md to ${outPath}\n`);
  }

  return output;
}
